version: '3'
services:

  odoo:
    image: odoo:13    
    depends_on: 
      - db
    ports:
      - "8069:8069"

  db:
    image: postgres:10
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
