version: '3'
services:

  odoo:
    image: odoo:13    
    depends_on: 
      - db
    ports:
      - "8069:8069"

  db:
    image: postgres:10
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "8070:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=made.adi@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=test123
